services:
  # configuración del microservicio 1
  micro-service1:
    image: node:18
    container_name: micro-service1
    working_dir: /app
    volumes:
      - ./ms-1:/app:z
    command: sh -c 'npm install && npm start'
    expose:
      - "3000" # SOLUCIÓN 3: abtracción de la tipología interna del sistema

  # configuración 1 de la copia del microservicio 1
  mico-service1-1:
    image: node:18
    container_name: micro-service1-1
    working_dir: /app
    volumes:
      - ./ms-1:/app:z
    command: sh -c 'npm install && npm start'
    expose:
      - "3000" # SOLUCIÓN 3: abtracción de la tipología interna del sistema

  # configuración 2 de la copia del microservicio 2
  micro-service1-2:
    image: node:18
    container_name: micro-service1-2
    working_dir: /app
    volumes:
      - ./ms-1:/app:z
    command: sh -c 'npm install && npm start'
    expose:
      - "3000" # SOLUCIÓN 3: abtracción de la tipología interna del sistema

  # configuración de proxy reverse
  nginx_proxy:
    image: nginx
    ports:
      - "80:80" # SOLUCIÓN 1: puerto único de entrada
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
    depends_on:
      - micro-service1
      - micro-service1-1
      - micro-service1-2
