# SOLUCIÓN 2: gestión de un proxy reverse
events {}

http {
    
    upstream backend_api {
        # SOLUCIÓN 4: balanceador del tráfico de forma equitativa
        server micro-service1:3000;
        server micro-service1-1:3000;
        server micro-service1-2:3000;
    }

    server {
        listen 80; # SOLUCIÓN 1: puerto único de entrada

        location /api/v1/saludo {
            proxy_pass http://backend_api; # SOLUCIÓN 2: gestión de un proxy reverse
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}